### ISSUE TITLE
Additional references

### ISSUE THREAD

**Issue by monpasang** [lexibank/bodtkhobwa#28]
This CLDF dataset was also used to come to the following articles, which should be mentioned in the repository on Zenodo:

Bodt, Timotheus Adrianus (accepted, 2021). The Duhumbi perspective on Proto-Western 	Kho-Bwa onsets. Journal of Historical Linguistics.

Bodt, Timotheus Adrianus. 2019. The Duhumbi perspective on Proto-Western Kho-Bwa 	rhymes. Die Sprache 52 (2016 / 2017) 2: 141-176.

**Comment by LinguList** [comment]
When is the big book going to appear? While we can add all references, and we can easily do so, adding them to the NOTES.md field, where additional information can be added, it might be best to publish/quote this dataset as Bodt (without List, who has nothing to do with the data apart from the processing of the forms for computational treatment). How about "CLDF dataset derived from Bodt's "Etymological Dictionary of Western Kho-Bwa"? The "how to quote" could then say something like:

> Bodt, T. A. (forthcoming): Etymological Dictionary of Western Kho-Bwa. Version 0.1. ADDRESS: Publisher.

I'd need publisher and address. Or otherwise, the affiliation you select (London, SOAS, whatever, let me know).

**Comment by LinguList** [comment]
@monpasang, I thought more about this, and it seems to me that it is best to treat different studies based on the Kho-Bwa data as if they use different versions of the data. The data in the studies on prediction and the CLICS paper all use essentially the same data file, as it is given in THIS package, which is provided in CLDF format.

The alternative studies are based on your evolving data, which surely is different in 2016 / 2017 from 2019, etc. So it is best to treat this as a single publication with different editions or a database with different versions and give the data a unifying name (as suggested in my note before). The advantage is that the data then can also "physically" be identified with a given file (bodt-khobwa-cleaned.tsv as the one we used for the predictions). We mention then in the notes, that other versions of the data have lead to other publications.

**Comment by monpasang** [comment]
Ok whatever.
